"""updated documents table

Revision ID: d7a461cd20db
Revises: eaf56c457baa
Create Date: 2026-06-11 21:01:19.999022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a461cd20db'
down_revision: Union[str, Sequence[str], None] = 'eaf56c457baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_hash', sa.Column('status', sa.Enum('uploaded', 'processing', 'embedded', 'failed', name='documentstatus'), nullable=True))
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', postgresql.ENUM('uploaded', 'processing', 'embedded', 'failed', name='documentstatus'), autoincrement=False, nullable=True))
    op.drop_column('document_hash', 'status')
    # ### end Alembic commands ###
