"""updated documents table

Revision ID: eaf56c457baa
Revises: 404d62dfff39
Create Date: 2026-06-11 20:55:42.603715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf56c457baa'
down_revision: Union[str, Sequence[str], None] = '404d62dfff39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_hash',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_hash_hash_value'), 'document_hash', ['hash_value'], unique=True)
    op.add_column('documents', sa.Column('document_hash_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    op.create_foreign_key(None, 'documents', 'document_hash', ['document_hash_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_column('documents', 'document_hash_id')
    op.drop_index(op.f('ix_document_hash_hash_value'), table_name='document_hash')
    op.drop_table('document_hash')
    # ### end Alembic commands ###
